# Generated by Django 5.2.16 on 2026-07-23 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeneratedDocument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('md', 'Markdown'), ('html', 'HTML'), ('docx', 'Word Document'), ('pdf', 'PDF')], max_length=10)),
                ('file', models.FileField(upload_to='exports/')),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='GeneratedDocument.generateddocument')),
            ],
            options={
                'unique_together': {('document', 'format')},
            },
        ),
    ]
