# Generated by Django 5.2.16 on 2026-07-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='template_instructions',
            field=models.TextField(blank=True),
        ),
    ]
