# Generated by Django 5.2.16 on 2026-07-20 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(default='srs', max_length=50)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('answers_complete', 'Answers Complete'), ('generating', 'Generating'), ('generated', 'Generated'), ('exported', 'Exported')], default='in_progress', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
