# Generated by Django 5.2.16 on 2026-07-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentSession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsession',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
