# Generated by Django 5.2.16 on 2026-07-23 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DocumentSession', '0001_initial'),
        ('Sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('polishing', 'Polishing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_sections', to='Sections.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_sections', to='DocumentSession.documentsession')),
            ],
            options={
                'unique_together': {('session', 'section')},
            },
        ),
    ]
