# Generated by Django 5.2.16 on 2026-07-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneratedSection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedsection',
            name='diagram_data_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generatedsection',
            name='diagram_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
